#CLUSTERING  OF PA'S FOR ABSTRACT AND RELATEDNESS MEASURES

#1) AIM: CREATE A DICTIONARY OF "BAD TERMS" TO EXCLUDE FROM FURTHER ANALYSIS
#   METHOD: TOKENISE ALL WORDS AND HISTOGRAM. SORT.
tokens = {}

pas = Pa.find_each( :select => 'DISTINCT name_eng, gid', :batch_size => 100 ) do |p|
  p.name_eng.split(/\W/).each do |t|
    tokens[t] ||=0
    tokens[t] += 1
  end
end
sorted_tokens = tokens.sort {|a,b| b[1]<=>a[1]}

puts sorted_tokens.inspect


#2) DECIDE HOW TO SPLIT HISTOGRAM TO REMOVE COMMON WORDS - THRESHOLD? USE SECOND DERIVATIVE?

#3) TOKENISE NAME_ENG, REMOVE BAD_TOKENS

#4) GENERATE DOUBLE METAPHONE FOR EACH TOKEN AND STORE WITH GID

#5) SELECT NEARBY PA's ONLY < 50k?

#6) CREATE PROXIMITY MATRIX USING TANIMOTO SIMILARITY INDEX ON METAPHONE SETS (RATIO OF INTERSECTS VS TOTAL UNION OF 2)

#7) CLUSTER based on threshold. Notes