--- 
embed_assets: on
javascripts: 
  register:
    - public/javascripts/register/main.js
  about:
    - public/javascripts/about/main.js
  country:
    - public/javascripts/country/country_map.js
  user:
    - public/javascripts/user/jquery.flip.js
    - public/javascripts/user/main.js
  home:
    - public/javascripts/home/gmaps_xml_util.js
    - public/javascripts/common/hoverIntent.js
    - public/javascripts/home/sparsetile.js
    - public/javascripts/common/jquery.autocomplete.js
    - public/javascripts/common/jquery.easing.1.3.js
    - public/javascripts/common/jquery.history.js
    - public/javascripts/common/jquery.cookies.2.1.0.js
    - public/javascripts/home/homeEffects.js
    - public/javascripts/home/homeMap.js
    - public/javascripts/home/PAInfoWindow.js
  site:
    - public/javascripts/home/sparsetile.js
    - public/javascripts/site/site_map.js
    - public/javascripts/site/site_marker.js
    - public/javascripts/site/main.js
  activity:
    - public/javascripts/activity/Activity_Marker.js
    - public/javascripts/activity/Fluster2ProjectionOverlay.js
    - public/javascripts/activity/Fluster2Cluster.js
    - public/javascripts/activity/Fluster2ClusterMarker.js
    - public/javascripts/activity/Fluster2.js
    - public/javascripts/activity/main.js
    - public/javascripts/activity/activity_map.js
  search:
    - public/javascripts/home/sparsetile.js
    - public/javascripts/search/search_map.js
    - public/javascripts/search/SearchMarker.js
    - public/javascripts/search/main.js
  base:
    - public/javascripts/common/jquery.jcarousel.js
    - public/javascripts/common/jquery.livequery.js
    - public/javascripts/common/jquery.simplemodal.js
    - public/javascripts/common/jquery.stylish-select.js
    - public/javascripts/common/hoverIntent.js
    - public/javascripts/common/flashobject.js
    - public/javascripts/common/jquery.tipsy.js
    - public/javascripts/common/jquery.autocomplete.js
    - public/javascripts/common/jquery.cookies.2.1.0.js
    - public/javascripts/common/easySlider1.7.js
    - public/javascripts/common/jquery.form.js
    - public/javascripts/common/jquery.json-2.2.js
    - public/javascripts/common/jquery.scrollTo.js
    - public/javascripts/common/underscore-min.js
    - public/javascripts/common/jquery.selectbox-0.6.js
    #- public/javascripts/application
    - public/javascripts/common/main.js
stylesheets: 
  base:
    - public/javascripts/layout.css
    - public/javascripts/tipsy.css
    - public/javascripts/jquery.autocomplete.css
