--- 
embed_assets: on
javascripts: 
  register:
    - register/main.js
  about:
    - about/main.js
  country:
    - country/country_map.js
  user:
    - user/jquery.flip.js
    - user/main.js
  home:
    - home/gmaps_xml_util.js
    - common/hoverIntent.js
    - home/sparsetile.js
    - common/jquery.autocomplete.js
    - common/jquery.easing.1.3.js
    - common/jquery.history.js
    - common/jquery.cookies.2.1.0.js
    - home/homeEffects.js
    - home/homeMap.js
    - home/PAInfoWindow.js
  site:
    - home/sparsetile.js
    - site/site_map.js
    - site/site_marker.js
    - site/main.js
  activity:
    - activity/Activity_Marker.js
    - activity/Fluster2ProjectionOverlay.js
    - activity/Fluster2Cluster.js
    - activity/Fluster2ClusterMarker.js
    - activity/Fluster2.js
    - activity/main.js
    - activity/activity_map.js
  search:
    - home/sparsetile.js
    - search/search_map.js
    - search/SearchMarker.js
    - search/main.js
  base:
    - common/jquery.jcarousel.js
    - common/jquery.livequery.js
    - common/jquery.simplemodal.js
    - common/jquery.stylish-select.js
    - common/hoverIntent.js
    - common/flashobject.js
    - common/jquery.tipsy.js
    - common/jquery.autocomplete.js
    - common/jquery.cookies.2.1.0.js
    - common/easySlider1.7.js
    - common/jquery.form.js
    - common/jquery.json-2.2.js
    - common/jquery.scrollTo.js
    - common/underscore-min.js
    - common/jquery.selectbox-0.6.js
    #- application
    - common/main.js
stylesheets: 
  base:
    - layout.css
    - tipsy.css
    - jquery.autocomplete.css
